# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "catcher"
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["seenmyfate"]
  s.date = "2014-12-03"
  s.description = "Catcher wraps JSON API calls, and stores the parsed hash in Memcached. Subsequent calls to the same API will either be returned directly from cache, or drop through to the API."
  s.email = "seenmyfate@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".ruby-version",
    ".travis.yml",
    "CONTRIBUTING.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "catcher.gemspec",
    "lib/catcher.rb",
    "lib/catcher/api.rb",
    "lib/catcher/cache.rb",
    "lib/catcher/cache_store.rb",
    "lib/catcher/core_ext/array.rb",
    "lib/catcher/encoder.rb",
    "lib/catcher/service.rb",
    "lib/catcher/service/net/http.rb",
    "lib/catcher/service/nil_api_response_error.rb",
    "spec/catcher_spec.rb",
    "spec/lib/catcher/api_spec.rb",
    "spec/lib/catcher/cache_spec.rb",
    "spec/lib/catcher/cache_store_spec.rb",
    "spec/lib/catcher/encoder_spec.rb",
    "spec/lib/catcher/service/net/http_spec.rb",
    "spec/lib/catcher/service_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/dummy_class.rb"
  ]
  s.homepage = "http://github.com/onthebeach/catcher"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23.2"
  s.summary = "Automatic caching for API calls"

  s.add_runtime_dependency 'yajl-ruby'
  s.add_runtime_dependency 'dalli'
  s.add_runtime_dependency 'log4r'
  s.add_runtime_dependency 'activesupport'
  s.add_development_dependency 'rspec'
  s.add_development_dependency 'yard'
  s.add_development_dependency 'bundler'
  s.add_development_dependency 'jeweler'
  s.add_development_dependency 'mocha'
  s.add_development_dependency 'redcarpet'
  s.add_development_dependency 'simplecov'
end

